apiVersion: 1

datasources:
  - name: MySQL via ProxySQL
    type: mysql
    access: proxy
    url: proxysql:6033
    user: grafana
    secureJsonData:
      password: grafana_change_me
    jsonData:
      database: app
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      tlsAuth: false
    isDefault: true

  - name: Loki - Docker logs
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
